
package UserInterface.WorkAreas.StudentRole;

import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.CourseSchedule.CourseSchedule;
import info5100.university.example.CourseSchedule.CourseOffer;
import info5100.university.example.CourseSchedule.CourseLoad;
import info5100.university.example.CourseSchedule.SeatAssignment;
import info5100.university.example.Department.Department; 

import javax.swing.JPanel;                                
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;

public class StudentRegistrationJPanel extends javax.swing.JPanel {
    private final JPanel workArea;
    private final Department dept;
    private final String personId;
    
    //use this helper for showing the message for selection status on lblMsg
    private void setStatus(String s) { lblMsg.setText(s == null ? " " : s); }
    
    //get schedule for a semester
    private CourseSchedule scheduleFor(String sem) {
        return (dept == null ? null : dept.getCourseSchedule(sem));
    }
    
    //check seats left on an offering course
    private int seatsLeft(CourseOffer co) {
        return co.getEmptySeatCount();
    }
    
    public StudentRegistrationJPanel(JPanel workArea, Department dept, String personId) {
        this.workArea = workArea;
        this.dept = dept;
        this.personId = personId;
        
        initComponents();
        lblMsg.setText(" "); //keep status bar visible even when empty.
        
        //initialize the semester list in comboBox
        cmbSemester.removeAllItems();
        cmbSemester.addItem("Fall2025");
        cmbSemester.addItem("Spring2026");
        cmbSemester.setSelectedIndex(0);
        
        //first load of both tables
        loadAvailable();
        loadEnrolled();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSemester = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        lblAvailable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrolled = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvailable1 = new javax.swing.JTable();
        lblEnrolled = new javax.swing.JLabel();
        btnDrop = new javax.swing.JButton();
        btnEnroll = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();

        lblSemester.setText("Semester");

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAvailable.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAvailable.setText("Available Offerings");

        tblEnrolled.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnrolled);

        tblAvailable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course", "Name", "Seats Left"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAvailable1);
        if (tblAvailable1.getColumnModel().getColumnCount() > 0) {
            tblAvailable1.getColumnModel().getColumn(2).setResizable(false);
            tblAvailable1.getColumnModel().getColumn(2).setHeaderValue("Seats Left");
        }

        lblEnrolled.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEnrolled.setText("My Enrollments");

        btnDrop.setText("Drop Course");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnEnroll.setText("Enroll Course");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        lblMsg.setBackground(new java.awt.Color(204, 204, 204));
        lblMsg.setText("\" \"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemester)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(btnDrop)
                                .addGap(18, 18, 18)
                                .addComponent(btnEnroll)
                                .addGap(18, 18, 18)
                                .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(lblEnrolled)
                    .addComponent(lblAvailable))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemester)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblAvailable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblEnrolled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDrop)
                    .addComponent(btnEnroll)
                    .addComponent(lblMsg)
                    .addComponent(btnBack))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
        loadAvailable();
        loadEnrolled();
        
    }//GEN-LAST:event_cmbSemesterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //wire the back button to Student Portal panel
        if (workArea != null) {
        ((CardLayout) workArea.getLayout()).previous(workArea);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        int row = tblAvailable1.getSelectedRow();
        if (row < 0) { setStatus("Select a course to enroll."); return; }

        String sem  = String.valueOf(cmbSemester.getSelectedItem());
        String cnum = String.valueOf(tblAvailable1.getValueAt(row, 0));

        CourseSchedule cs = scheduleFor(sem);
        if (cs == null) { setStatus("No schedule for " + sem); return; }
        
        //find the offer by course number
        CourseOffer co = cs.getCourseOfferByNumber(cnum);
        if (co == null) { setStatus("Course not found."); return; }

        if (seatsLeft(co) <= 0) { setStatus("No seats left."); return; }

        StudentProfile sp = getOrCreateModelStudent();
        
        //Ensure there is a CourseLoad for this semester, then enroll
        CourseLoad cl = sp.getCourseLoadBySemester(sem);
        if (cl == null) cl = sp.newCourseLoad(sem);
        
        SeatAssignment sa = cl.newSeatAssignment(co);
        if (sa == null) { setStatus("Seat could not be assigned."); return; }
        
        
        setStatus("Enrolled in " + cnum + " (" + sem + ").");
        loadAvailable();
        loadEnrolled();
        
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
        int row = tblEnrolled.getSelectedRow();
        if (row < 0) { setStatus("Select a course to drop."); return; }

        String sem  = String.valueOf(cmbSemester.getSelectedItem());
        String cnum = String.valueOf(tblEnrolled.getValueAt(row, 0));

        CourseSchedule cs = scheduleFor(sem);
        if (cs == null) { setStatus("No schedule for " + sem); return; }

        CourseOffer co = cs.getCourseOfferByNumber(cnum);
        if (co == null) { setStatus("Course not found."); return; }

        StudentProfile sp = getOrCreateModelStudent();
        CourseLoad cl = sp.getCourseLoadBySemester(sem);
        if (cl == null) { setStatus("Nothing to drop."); return; }
        
        // find the seat assignment for this offer
        SeatAssignment target = null;
        for (SeatAssignment sa : new java.util.ArrayList<>(cl.getSeatAssignments())) {
            if (sa.getCourseOffer() == co) { target = sa; break; }
        }
        if (target == null) { setStatus("You are not enrolled in " + cnum + "."); return; }
        
        // remove from this semester’s courseload
        cl.getSeatAssignments().remove(target);

        setStatus("Dropped " + cnum + " (" + sem + ").");
        loadAvailable();
        loadEnrolled();
        
    }//GEN-LAST:event_btnDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblEnrolled;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JTable tblAvailable1;
    private javax.swing.JTable tblEnrolled;
    // End of variables declaration//GEN-END:variables

    //populate the Available table for the selected semester
    private void loadAvailable() {
        DefaultTableModel m = (DefaultTableModel) tblAvailable1.getModel();
        m.setRowCount(0);

        String sem = String.valueOf(cmbSemester.getSelectedItem());
        CourseSchedule cs = scheduleFor(sem);
        if (cs == null) { setStatus("No schedule for " + sem); return; }

        // common API: cs.getSchedule().values() returns the CourseOffers
        for (CourseOffer co : cs.getCourseOfferList()) {
            String num  = co.getCourseNumber();
            String name = co.getSubjectCourse().getName();
            int left    = seatsLeft(co);
            m.addRow(new Object[]{num, name, left});
        }
        setStatus(" ");
        }

    //populate My Enrollments for the selected semester
    private void loadEnrolled() {
        DefaultTableModel m = (DefaultTableModel) tblEnrolled.getModel();
        m.setRowCount(0);

        String sem = String.valueOf(cmbSemester.getSelectedItem());
        StudentProfile sp = getOrCreateModelStudent();
        CourseLoad cl = sp.getCourseLoadBySemester(sem); // from our StudentProfile

        if (cl == null) return;

        for (SeatAssignment sa : cl.getSeatAssignments()) {
            CourseOffer co = sa.getCourseOffer();
            String num  = co.getCourseNumber();
            String name = co.getSubjectCourse().getName();
            m.addRow(new Object[]{num, name});
        
        }
    }

    private StudentProfile getOrCreateModelStudent() {
        PersonDirectory pd = dept.getPersonDirectory();
        Person mp = pd.findPerson(personId);
        if (mp == null) mp = pd.newPerson(personId);

        StudentDirectory sd = dept.getStudentDirectory();
        StudentProfile sp = sd.findStudent(personId);
        if (sp == null) sp = sd.newStudentProfile(mp);
        return sp;
        }
    
}
