
package UserInterface.WorkAreas.StudentRole;

import info5100.university.example.Persona.Person;
import info5100.university.example.Persona.PersonDirectory;
import info5100.university.example.Persona.StudentDirectory;
import info5100.university.example.Persona.StudentProfile;
import info5100.university.example.Department.Department;

import javax.swing.JPanel;
import java.awt.CardLayout;

public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    private final JPanel workArea; 
    private final Department dept; 
    private final String personId;  

    /**
     * Creates new form UnitRiskWorkArea
     * @param b
     * @param spp
     * @param clp
     */

    public StudentWorkAreaJPanel(JPanel workArea, String personId, Department dept) {
        initComponents();
        this.workArea = workArea;
        this.dept = dept;
        this.personId = personId;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCourseWork = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();
        btnRegistration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTranscript = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnCourseWork.setBackground(new java.awt.Color(102, 153, 255));
        btnCourseWork.setFont(getFont());
        btnCourseWork.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseWork.setText("Course Work");
        btnCourseWork.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCourseWork.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCourseWork.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCourseWork.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCourseWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseWorkIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnManageProfile.setFont(getFont());
        btnManageProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnGraduationAudit.setBackground(new java.awt.Color(102, 153, 255));
        btnGraduationAudit.setFont(getFont());
        btnGraduationAudit.setForeground(new java.awt.Color(255, 255, 255));
        btnGraduationAudit.setText("Graduation Audit");
        btnGraduationAudit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGraduationAudit.setMaximumSize(new java.awt.Dimension(200, 40));
        btnGraduationAudit.setMinimumSize(new java.awt.Dimension(20, 20));
        btnGraduationAudit.setPreferredSize(new java.awt.Dimension(240, 25));
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        btnRegistration.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistration.setFont(getFont());
        btnRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistration.setText("Registration");
        btnRegistration.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistration.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegistration.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegistration.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("My Student Portal");

        btnTranscript.setBackground(new java.awt.Color(102, 153, 255));
        btnTranscript.setFont(getFont());
        btnTranscript.setForeground(new java.awt.Color(255, 255, 255));
        btnTranscript.setText("Transcript");
        btnTranscript.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTranscript.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTranscript.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTranscript.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnTranscript, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCourseWork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseWorkIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseWorkIdentifyResourceAssetsActionPerformed
        String name = "CourseWork";
        CourseWorkJPanel panel = new CourseWorkJPanel(workArea, dept, personId);
        workArea.add(name, panel);
        ((java.awt.CardLayout) workArea.getLayout()).show(workArea, name);

    }//GEN-LAST:event_btnCourseWorkIdentifyResourceAssetsActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        String name = "StudentMyProfile";
        StudentProfile sp = getOrCreateModelStudent();
        StudentMyProfileJPanel panel = new StudentMyProfileJPanel(sp,workArea,dept); 
        workArea.add(name, panel);
        ((CardLayout) workArea.getLayout()).show(workArea, name);

}//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        // TODO add your handling code here:
        String name = "Graduat Audit";
        GraduationAuditJPanel ga = new GraduationAuditJPanel(workArea, dept, personId);
        workArea.add(name, ga);
        ((java.awt.CardLayout) workArea.getLayout()).show(workArea, name);


    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        // TODO add your handling code here:
        StudentRegistrationJPanel p = new StudentRegistrationJPanel(workArea, dept, personId);
        workArea.add("studentReg", p);
        ((CardLayout) workArea.getLayout()).show(workArea, "studentReg");

}//GEN-LAST:event_btnRegistrationActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTranscriptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseWork;
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private StudentProfile getOrCreateModelStudent() {
        PersonDirectory pd = dept.getPersonDirectory();
        Person mp = pd.findPerson(personId);
        if (mp == null) mp = pd.newPerson(personId);

        StudentDirectory sd = dept.getStudentDirectory();
        StudentProfile sp = sd.findStudent(personId);
        if (sp == null) sp = sd.newStudentProfile(mp);
        return sp;
        
    }
    

}
